import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {createApi} from '../server/api.mjs';
test('verified identity linking preserves votes/admin and blocks takeover and legacy bypass',async()=>{
 const db=new PGlite();
 for(const file of ['202609060001_initial.sql','202609080001_email_identity.sql'])await db.exec(await readFile('netlify/database/migrations/'+file,'utf8'));
 const handle=createApi({query:async(s,p)=>(await db.query(s,p)).rows});
 const call=async(path,body,identityUser=null,cookie='',enabled=true,origin='https://example.test')=>{const r=await handle(new Request('https://example.test/api'+path,{headers:{origin,cookie,'content-type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})}),{emailIdentityEnabled:enabled,identityUser,ip:'test'});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const old=await call('/signup',{username:'owner',password:'original-password-123'},null,'',false);
 await db.query('UPDATE users SET is_admin=true WHERE id=$1',[old.data.user.id]);
 await call('/vote',{product_id:'opi-top-coat',choice:'slay'},null,old.cookie,false);
 const identity={id:'verified-id',email:'owner@example.test',confirmedAt:new Date().toISOString(),userMetadata:{is_admin:true}};
 assert.equal((await call('/signup',{username:'bypass',password:'some-password-123'})).status,400);
 assert.equal((await call('/vote',{product_id:'opi-top-coat',choice:'nay'},null,old.cookie)).status,403);
 assert.equal((await call('/identity/complete',{username:'owner',link:true,password:'original-password-123'},{...identity,confirmedAt:null})).status,401);
 assert.equal((await call('/identity/complete',{username:'owner'},identity)).status,409);
 assert.equal((await call('/identity/complete',{username:'owner',link:true,password:'incorrect-password-123'},identity)).status,401);
 assert.equal((await call('/identity/complete',{username:'owner',link:true,password:'original-password-123'},identity,'',true,'https://evil.test')).status,403);
 const linked=await call('/identity/complete',{username:'owner',link:true,password:'original-password-123'},identity);
 assert.equal(linked.data.user.id,old.data.user.id);assert.equal(linked.data.user.is_admin,true);
 assert.equal((await call('/me',null,null,old.cookie)).data.user,null);
 assert.equal((await call('/signin',{username:'owner',password:'original-password-123'})).status,400);
 assert.equal((await call('/identity/complete',{username:'owner',link:true,password:'original-password-123'},{...identity,id:'attacker'})).status,409);
 assert.equal((await call('/vote/change',{product_id:'opi-top-coat',choice:'nay'},identity)).status,200);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM votes WHERE user_id=$1',[old.data.user.id])).rows[0].n,1);
 const newbie=await call('/identity/complete',{username:'new_member'},{...identity,id:'new-id',email:'new@example.test'});
 assert.equal(newbie.status,201);assert.equal(newbie.data.user.is_admin,false);
 await db.close();
});
